// <auto-generated />
using System;
using EmployeeInfoSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeInfoSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705160230_AddRequestTypesSeed")]
    partial class AddRequestTypesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeInfoSystem.Domain.EmployeeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BornDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("born_date");

                    b.Property<int?>("ClothesSize")
                        .HasColumnType("integer")
                        .HasColumnName("size_clothes");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fio")
                        .HasColumnType("text")
                        .HasColumnName("fio");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("post");

                    b.Property<int?>("ShoesSize")
                        .HasColumnType("integer")
                        .HasColumnName("size_shoes");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Tabn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabn");

                    b.Property<int?>("WinterClothesSize")
                        .HasColumnType("integer")
                        .HasColumnName("size_clothes_winter");

                    b.Property<int?>("WinterShoesSize")
                        .HasColumnType("integer")
                        .HasColumnName("size_shoes_winter");

                    b.HasKey("Id");

                    b.HasIndex("Tabn")
                        .IsUnique();

                    b.ToTable("employeecache", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("RecipientId1")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<int?>("SenderId1")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("RecipientId1");

                    b.HasIndex("RequestId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SenderId1");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.Ppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("GiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("give_date");

                    b.Property<string>("GroupName")
                        .HasColumnType("text")
                        .HasColumnName("group_name");

                    b.Property<string>("ItemName")
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Tabn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabn");

                    b.Property<int?>("WearPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("wear_period");

                    b.HasKey("Id");

                    b.ToTable("ppecache", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.RecipientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("recipient_groups", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("integer");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<int?>("ManagerId1")
                        .HasColumnType("integer");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("request_type_id");

                    b.Property<int?>("RequestTypeId1")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionComment")
                        .HasColumnType("text")
                        .HasColumnName("resolution_comment");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ManagerId1");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequestTypeId1");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("requesttypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CHANGE_CONTACTS",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Изменение контактных данных"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CHANGE_SIZES",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Изменение размеров спецодежды"
                        });
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PushToken")
                        .HasColumnType("text")
                        .HasColumnName("push_token");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Tabn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabn");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.EmployeeProfile", b =>
                {
                    b.HasOne("EmployeeInfoSystem.Domain.User", null)
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("EmployeeInfoSystem.Domain.EmployeeProfile", "Tabn")
                        .HasPrincipalKey("EmployeeInfoSystem.Domain.User", "Tabn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.News", b =>
                {
                    b.HasOne("EmployeeInfoSystem.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.Notification", b =>
                {
                    b.HasOne("EmployeeInfoSystem.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EmployeeInfoSystem.Domain.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId1");

                    b.HasOne("EmployeeInfoSystem.Domain.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("EmployeeInfoSystem.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EmployeeInfoSystem.Domain.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId1");

                    b.Navigation("Recipient");

                    b.Navigation("Request");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.Request", b =>
                {
                    b.HasOne("EmployeeInfoSystem.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EmployeeInfoSystem.Domain.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("EmployeeInfoSystem.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EmployeeInfoSystem.Domain.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId1");

                    b.HasOne("EmployeeInfoSystem.Domain.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EmployeeInfoSystem.Domain.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId1");

                    b.Navigation("Employee");

                    b.Navigation("Manager");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("EmployeeInfoSystem.Domain.User", b =>
                {
                    b.Navigation("EmployeeProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
